extends: ["@stoplight/spectral-owasp-ruleset"]

rules:
  "owasp:api4:2019-rate-limit": warn
  "owasp:api2:2019-protection-global-unsafe" : warn
  "owasp:api4:2019-string-limit":
    message: "Schema of type string must specify maxLength!"
    description: "String size should be limited to mitigate resource exhaustion attacks. This can be done using `maxLength`."
    severity: error
    given: '$..[?(@ && @.type=="string")]'
    then:
      function: schema
      functionOptions:
        schema:
          type: object
          anyOf:
            - required: ["maxLength"]
            - required: ["enum"]
            - required: ["const"]           
            - required: 
                format:
                  properties:
                    type: string
                    enum:
                      - uuid
                      - date
                      - date-time
  additional-properties:
    description: Additional properties must be forbidden in every object
    given: '$..[?(@ && @.type=="object")]'
    severity: error
    then:
      function: schema
      functionOptions:
        schema:
          type: object
          required:
            - additionalProperties
          properties:
            additionalProperties:
            const: false