openapi: '3.0.2'
info:
  title: Quotation API
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /rfqs:
    post:
      operationId: create-rfq
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Quotation"
      responses:
        '200':
          description: OK
components:
  schemas:
    Quotation:
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
          format: uuid
        product:
          type: string
          maxLength: 20
          pattern: '(\w+\W*)*'
        quantity:
          type: integer
          format: int32
          minimum: 0
          maximum: 1000
        price:
          type: string
        shipment:
          type: string
          enum:
            - FOB
            - DAT
        mode:
          type: string
          pattern: "[A-Z]{3}"
          maxLength: 3